name = "FullShell"
uuid = "7d6ffa35-d0d1-47cf-a89d-5cba1c019934"
authors = ["Carlos Pay√°"]
version = "1.0.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Quantica = "ae5ea0c6-3f5e-46a2-bc28-a7c4c7a4773c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
Parameters = "~0.12"
Quantica = "~1"
Roots = "~2.1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]