name = "FullShell"
uuid = "7d6ffa35-d0d1-47cf-a89d-5cba1c019934"
version = "1.4.0"
authors = ["Carlos Pay√°"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Quantica = "ae5ea0c6-3f5e-46a2-bc28-a7c4c7a4773c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.12.0"
Parameters = "~0.12"
Quantica = "~1"
Roots = "~2.1"
StaticArrays = "1.9.17"
julia = "1.9"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["Documenter"]
test = ["Test"]
